[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PORT = "10000"
PYTHON_VERSION = "3.10.12"

[environments.production.plugins.postgresql]