services:
  - type: web
    name: hawk-esports-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: "10000"