services:
  - type: web
    name: hawk-esports-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PUBG_API_KEY
        sync: false
      - key: MEDAL_API_KEY
        sync: false
      - key: BOT_PREFIX
        value: "!"
      - key: RENDER
        value: "true"
      - key: WEB_PORT
        value: "10000"
      - key: WEB_HOST
        value: "0.0.0.0"
    autoDeploy: true
    healthCheckInterval: 60
    disk:
      name: hawk-bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1